Repository citizenfx/fivem-docs, pull requests merged in 2024-08, with the labels that each got.

#276 Simplify readability with all-in-one RegisterNetEvent
  content/docs/scripting-manual/working-with-events/listening-for-events.md
  content/docs/scripting-reference/runtimes/lua/functions/TriggerClientEvent.md
Labels: ready-to-merge

#326 Update vehicleComponentControlEvent.md
  content/docs/scripting-reference/events/list/vehicleComponentControlEvent.md
Labels: ready-to-merge

#380 Add JavaScript exports typings
  content/docs/scripting-manual/runtimes/javascript.md
Labels: ready-to-merge

#412 Reference AddStateBagChangeHandler to docs.
  content/docs/scripting-manual/networking/state-bags.md
Labels: ready-to-merge

#237 Added a note in regards to the order depending on game build
  content/docs/game-references/checkpoints.md
Labels: ready-to-merge

#292 Add js examples
  content/docs/resources/baseevents/_index.md
  content/docs/resources/baseevents/events/onPlayerDied.md
  content/docs/resources/baseevents/events/onPlayerKilled.md
  content/docs/resources/mapmanager/events/onClientGameTypeStart.md
Labels: ready-to-merge

#351 Update resource-manifest.md
  content/docs/scripting-reference/resource-manifest/resource-manifest.md
Labels: ready-to-merge

#456 feat(net): support dynamic server endpoints using handover
  content/docs/scripting-reference/events/list/playerConnecting.md
Labels: ready-to-merge

#459 feat(docs/blips): Animated Blips
  content/docs/game-references/blips.md
  static/blips/radar_enemy_heli_spin.gif
  static/blips/radar_enemy_heli_spin.png
  static/blips/radar_enemy_heli_spin_anim.png
  static/blips/radar_higher.gif
  static/blips/radar_higher.png
  static/blips/radar_higher_ai.gif
  static/blips/radar_higher_ai.png
  static/blips/radar_lower.gif
  static/blips/radar_lower.png
  static/blips/radar_lower_ai.gif
  static/blips/radar_lower_ai.png
  static/blips/radar_mp_noise.gif
  static/blips/radar_mp_noise.png
  static/blips/radar_player_heli.gif
  static/blips/radar_player_heli.png
  static/blips/radar_player_heli_spin_anim.png
  static/blips/radar_police.gif
  static/blips/radar_police.png
  static/blips/radar_police_chase.gif
  static/blips/radar_police_chase.png
  static/blips/radar_police_chase_anim.png
  static/blips/radar_police_heli_spin.gif
  static/blips/radar_police_heli_spin.png
  static/blips/radar_police_heli_spin_anim.png
  static/blips/radar_police_ped.gif
  static/blips/radar_police_ped.png
  static/blips/radar_weapon_higher.gif
  static/blips/radar_weapon_higher.png
  static/blips/radar_weapon_lower.gif
  static/blips/radar_weapon_lower.png
Labels: ready-to-merge

#460 feat(docs/references): b3258 Blips
  content/docs/game-references/blips.md
  static/blips/radar_aircraft_carrier.png
  static/blips/radar_animal_possessed.png
  static/blips/radar_bail_bonds_office.png
  static/blips/radar_bounty_target.png
  static/blips/radar_daily_bounty.png
  static/blips/radar_filming_schedule.png
  static/blips/radar_maude_eccles.png
  static/blips/radar_mobile_phone.png
  static/blips/radar_office_transporter.png
  static/blips/radar_pizza_this.png
  static/blips/radar_weapon_emp.png
  static/blips/radar_weapon_emp_mine.png
  static/blips/radar_yankton_survival.png
  static/blips/radar_zombie_disease.png
  static/blips/radar_zombie_fire.png
  static/blips/radar_zombie_proximity.png
Labels: ready-to-merge

#438 refactor(intro/resources): update methods
  content/docs/scripting-manual/introduction/introduction-to-resources.md
Labels: ready-to-merge

#427 tweak(docs/commands): add a note that rcon uses UDP
  content/docs/server-manual/server-commands.md
Labels: ready-to-merge

#334 Create documentation contribution FAQ
  content/docs/support/documentation-faq.md
Labels: ready-to-merge

#448 refactor(readme/doc): update page
  README.md
Labels: ready-to-merge

#349 Added a new Game Event
  content/docs/game-references/game-events.md
Labels: ready-to-merge

#450 docs(server/commands): document ConVar 'sv_enableNetworkedScriptEntityStates'
  content/docs/server-manual/server-commands.md
Labels: ready-to-merge

#335 Workaround for scaleform boilerplate download
  content/docs/scripting-manual/using-scaleform/_index.md
  static/examples/using-scaleform/boilerplate.zip
Labels: ready-to-merge

#446 tweak(onesync/doc): updated version
  content/docs/support/server-issues.md
Labels: ready-to-merge

#440 feat(cfx.ini/page): new doc
  content/docs/client-manual/_index.md
  content/docs/client-manual/citizenfx.md
Labels: ready-to-merge

#435 feat(developpers/docs): setup guidelines
  content/docs/contributing/how-you-can-help.md
  content/docs/developers/_index.md
Labels: ready-to-merge

#374 Add radio stations and pickup hashes
  content/docs/game-references/_index.md
  content/docs/game-references/pickup-hashes.md
  content/docs/game-references/radiostations.md
Labels: ready-to-merge

#416 Add License Types & Providers
  content/docs/scripting-reference/runtimes/lua/functions/GetPlayerIdentifiers.md
Labels: ready-to-merge

#420 refactor(page/framework): new descriptions and frameworks
  content/docs/server-manual/frameworks.md
Labels: ready-to-merge

#463 feat(scripting/ref): new index page
  content/docs/scripting-reference/_index.md
Labels: ready-to-merge

#454 feat(gamebuild/update): Bottom Dollar Bounties
  content/docs/server-manual/server-commands.md
Labels: ready-to-merge

#340 FiveM on Linux
  content/docs/support/client-faq.md
Labels: ready-to-merge

#432 feat(event/doc): trigger method
  content/docs/scripting-reference/runtimes/lua/functions/TriggerEvent.md
Labels: ready-to-merge

#355 Correct typos throughout docs wiki.
  content/docs/fxdk/_index.md
  content/docs/fxdk/world-editor.md
  content/docs/game-references/input-mapper-parameter-ids/digitalbutton_axis.md
  content/docs/game-references/input-mapper-parameter-ids/game_controlled.md
  content/docs/game-references/input-mapper-parameter-ids/mkb_axis.md
  content/docs/game-references/input-mapper-parameter-ids/touchpad_centered_axis.md
  content/docs/resources/mapmanager/_index.md
  content/docs/scripting-manual/introduction/fact-sheet.md
  content/docs/scripting-manual/runtimes/csharp.md
  content/docs/scripting-manual/using-scaleform/_index.md
  content/docs/scripting-reference/runtimes/lua/functions/Citizen.SetTimeout.md
  content/docs/scripting-reference/runtimes/lua/functions/Citizen.Wait.md
  content/docs/scripting-reference/runtimes/lua/functions/quat.md
  content/docs/server-manual/migrating-from-citmp.md
  content/docs/server-manual/server-commands.md
  content/docs/support/ban-faq.md
Labels: ready-to-merge

#447 feat(game-refs/vehicle-models): now using html to draw vehicle models
  content/docs/game-references/vehicle-models.md
Labels: ready-to-merge

#430 feat(native/doc): first understanding
  content/docs/scripting-manual/introduction/about-native-functions.md
  content/docs/scripting-reference/runtimes/lua/functions/Citizen.InvokeNative.md
Labels: ready-to-merge

#431 feat(wait/doc): complete page
  content/docs/scripting-reference/runtimes/lua/functions/Citizen.Wait.md
Labels: ready-to-merge

#467 Disable Antivirus scanning on FXServer directories
  content/docs/server-manual/setting-up-a-server-txadmin.md
  content/docs/server-manual/setting-up-a-server-vanilla.md
  content/docs/support/server-issues.md
Labels: Requires team approval, ready-to-merge

#468 Update Server/Client issues section
  content/docs/support/client-issues.md
  content/docs/support/server-issues.md
Labels: Requires team approval, ready-to-merge

#413 Add playerEnteredScope/playerLeftScope examples
  content/docs/scripting-reference/onesync/_index.md
Labels: ready-to-merge

#436 tweak(docs/links): use cfx articles
  content/docs/client-manual/_index.md
  content/docs/client-manual/console-commands.md
  content/docs/client-manual/installing-fivem.md
  content/docs/client-manual/system-requirements.md
  content/docs/client-manual/where-to-buy-gtav.md
  content/docs/fxdk/_index.md
  content/docs/support/_index.md
  content/docs/support/client-issues.md
Labels: Requires team approval, ready-to-merge

#462 feat(event/doc): trigger server method
  content/docs/scripting-reference/runtimes/lua/functions/TriggerServerEvent.md
Labels: waiting for review

#457 feat(doc): add security guideline
  content/docs/developers/server-security.md
Labels: waiting for review

#442 feat(shortcut/page): new doc
  content/docs/client-manual/_index.md
  content/docs/client-manual/shortcut.md
Labels: waiting for review

#472 Docs: NRT description and example
  content/docs/game-references/text-formatting.md
Labels: ready-to-merge
